### ISSUE TITLE
config.ini Example Needed

### ISSUE THREAD

**Issue by DougEubanks** [anderskvist/GoGMC320#1]
I'm unable to find any documentation or example config.ini.

**Comment by DougEubanks** [comment]
[radmon.org]
user = [USERNAME]
password = [DATA SUBMISSION PASSWORD]

[influxdb]
url = http://[IP]:8086/
user = [IF NEEDED, OTHERWISE BLANK]
password = [IF NEEDED, OTHERWISE BLANK]
database = [DB]

**Comment by KvistA-ELS** [comment]
Hi @DougEubanks 

Thanks, it must have slipped when I added it - I'll make sure to add one to the code.

You may very well be the first user of this code :D

/Anders
